#Cookie segura en produccion (requiere HTTPS)
app.cookie.secure=${COOKIE_SECURE:false}


# Desactivar logs de SQL y Spring Security en producción
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.springframework.security=WARN
logging.level.root=INFO

# Desactivar DevTools
spring.devtools.restart.enabled=false

# Habilitar cache
spring.web.resources.cache.period=86400
spring.web.resources.chain.cache=true


spring.main.lazy-initialization=false

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=10000 

server.tomcat.threads.max=60
server.tomcat.accept-count=50

spring.jmx.enabled=false

# Escuchar solo en localhost
# server.address=127.0.0.1

