--
-- PostgreSQL database dump
--

\restrict wXuWLZSTozvq6T2RXDL4ScJ8tg8knKGYgLjosuexL1ABcUgNH5oAeVtc0qIgfbE

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-02-10 01:52:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 24716)
-- Name: asistencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asistencia (
    dni character varying(255) NOT NULL,
    fecha_hora timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado_asistencia character varying(255)
);


ALTER TABLE public.asistencia OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 24841)
-- Name: detalle_pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_pago (
    id_pago integer NOT NULL,
    numero integer NOT NULL,
    id_producto integer,
    id_sm integer,
    cantidad integer DEFAULT 1,
    precio_unitario numeric(10,2) NOT NULL,
    subtotal numeric(10,2) GENERATED ALWAYS AS (((cantidad)::numeric * precio_unitario)) STORED,
    CONSTRAINT ck_producto_o_membresia CHECK ((((id_producto IS NULL) AND (id_sm IS NOT NULL)) OR ((id_producto IS NOT NULL) AND (id_sm IS NULL)))),
    CONSTRAINT detalle_pago_precio_unitario_check CHECK ((precio_unitario > (0)::numeric))
);


ALTER TABLE public.detalle_pago OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 24878)
-- Name: ejercicio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ejercicio (
    id_ejercicio integer NOT NULL,
    id_grupo integer NOT NULL,
    nombre character varying(255) NOT NULL,
    video_url character varying(255),
    descripcion character varying(255)
);


ALTER TABLE public.ejercicio OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 24877)
-- Name: ejercicio_id_ejercicio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ejercicio_id_ejercicio_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ejercicio_id_ejercicio_seq OWNER TO postgres;

--
-- TOC entry 5201 (class 0 OID 0)
-- Dependencies: 237
-- Name: ejercicio_id_ejercicio_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ejercicio_id_ejercicio_seq OWNED BY public.ejercicio.id_ejercicio;


--
-- TOC entry 223 (class 1259 OID 24738)
-- Name: empleado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empleado (
    dni character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    telefono character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    fecha_nacimiento date NOT NULL,
    id_puesto integer NOT NULL,
    fecha_inicio date DEFAULT CURRENT_DATE,
    activo boolean DEFAULT true
);


ALTER TABLE public.empleado OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 49215)
-- Name: gasto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gasto (
    id_gasto integer NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    monto numeric(10,2) NOT NULL,
    categoria character varying(255) NOT NULL,
    proveedor character varying(255) NOT NULL,
    id_mediopago integer NOT NULL,
    activo boolean DEFAULT true,
    CONSTRAINT gasto_categoria_check CHECK (((categoria)::text = ANY (ARRAY[('ALQUILER'::character varying)::text, ('SERVICIOS'::character varying)::text, ('SUELDOS'::character varying)::text, ('INSUMOS'::character varying)::text]))),
    CONSTRAINT gasto_monto_check CHECK ((monto > (0)::numeric))
);


ALTER TABLE public.gasto OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 49214)
-- Name: gasto_id_gasto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gasto ALTER COLUMN id_gasto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gasto_id_gasto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 24869)
-- Name: grupo_muscular; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grupo_muscular (
    id_grupo integer NOT NULL,
    nombre character varying(255) NOT NULL
);


ALTER TABLE public.grupo_muscular OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 24868)
-- Name: grupo_muscular_id_grupo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.grupo_muscular_id_grupo_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grupo_muscular_id_grupo_seq OWNER TO postgres;

--
-- TOC entry 5202 (class 0 OID 0)
-- Dependencies: 235
-- Name: grupo_muscular_id_grupo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.grupo_muscular_id_grupo_seq OWNED BY public.grupo_muscular.id_grupo;


--
-- TOC entry 229 (class 1259 OID 24782)
-- Name: medio_pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medio_pago (
    id_mediopago integer NOT NULL,
    nombre character varying(255) NOT NULL
);


ALTER TABLE public.medio_pago OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24781)
-- Name: medio_pago_id_mediopago_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.medio_pago_id_mediopago_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.medio_pago_id_mediopago_seq OWNER TO postgres;

--
-- TOC entry 5203 (class 0 OID 0)
-- Dependencies: 228
-- Name: medio_pago_id_mediopago_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.medio_pago_id_mediopago_seq OWNED BY public.medio_pago.id_mediopago;


--
-- TOC entry 225 (class 1259 OID 24756)
-- Name: membresia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.membresia (
    id_membresia integer NOT NULL,
    nombre character varying(255) NOT NULL,
    duracion_dias integer NOT NULL,
    precio_sugerido numeric(10,2) NOT NULL,
    activo boolean,
    asistencias_por_semana integer,
    tipo_membresia character varying(255),
    CONSTRAINT membresia_duracion_dias_check CHECK ((duracion_dias > 0)),
    CONSTRAINT membresia_precio_sugerido_check CHECK ((precio_sugerido > (0)::numeric)),
    CONSTRAINT membresia_tipo_membresia_check CHECK (((tipo_membresia)::text = ANY ((ARRAY['MUSCULACION'::character varying, 'FUNCIONAL'::character varying, 'MIXTA'::character varying])::text[])))
);


ALTER TABLE public.membresia OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 24755)
-- Name: membresia_id_membresia_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.membresia_id_membresia_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.membresia_id_membresia_seq OWNER TO postgres;

--
-- TOC entry 5204 (class 0 OID 0)
-- Dependencies: 224
-- Name: membresia_id_membresia_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.membresia_id_membresia_seq OWNED BY public.membresia.id_membresia;


--
-- TOC entry 231 (class 1259 OID 24791)
-- Name: pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pago (
    id_pago integer NOT NULL,
    id_mediopago integer NOT NULL,
    dni_empleado character varying(255) NOT NULL,
    dni_socio character varying(255),
    estado character varying(255) NOT NULL,
    fecha date DEFAULT CURRENT_DATE,
    monto numeric(10,2) NOT NULL
);


ALTER TABLE public.pago OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 24790)
-- Name: pago_id_pago_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pago_id_pago_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pago_id_pago_seq OWNER TO postgres;

--
-- TOC entry 5205 (class 0 OID 0)
-- Dependencies: 230
-- Name: pago_id_pago_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pago_id_pago_seq OWNED BY public.pago.id_pago;


--
-- TOC entry 227 (class 1259 OID 24769)
-- Name: producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto (
    id_producto integer NOT NULL,
    nombre character varying(255) NOT NULL,
    precio_sugerido numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    version integer DEFAULT 0,
    CONSTRAINT chk_producto_stock_no_negativo CHECK ((stock >= 0)),
    CONSTRAINT producto_precio_sugerido_check CHECK ((precio_sugerido > (0)::numeric)),
    CONSTRAINT producto_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.producto OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 24768)
-- Name: producto_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.producto_id_producto_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.producto_id_producto_seq OWNER TO postgres;

--
-- TOC entry 5206 (class 0 OID 0)
-- Dependencies: 226
-- Name: producto_id_producto_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.producto_id_producto_seq OWNED BY public.producto.id_producto;


--
-- TOC entry 222 (class 1259 OID 24730)
-- Name: puesto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.puesto (
    id_puesto integer NOT NULL,
    nombre character varying(255) NOT NULL
);


ALTER TABLE public.puesto OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24729)
-- Name: puesto_id_puesto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.puesto_id_puesto_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.puesto_id_puesto_seq OWNER TO postgres;

--
-- TOC entry 5207 (class 0 OID 0)
-- Dependencies: 221
-- Name: puesto_id_puesto_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.puesto_id_puesto_seq OWNED BY public.puesto.id_puesto;


--
-- TOC entry 239 (class 1259 OID 24892)
-- Name: rutina; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rutina (
    dni_empleado character varying(255),
    descripcion character varying(255),
    nombre character varying(255) NOT NULL,
    fecha date DEFAULT CURRENT_DATE,
    dni_socio character varying(255),
    id_rutina integer NOT NULL,
    id_plantilla_origen integer,
    personalizada boolean DEFAULT false NOT NULL
);


ALTER TABLE public.rutina OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 57444)
-- Name: rutina_detalle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rutina_detalle (
    id_detalle bigint NOT NULL,
    id_rutina integer NOT NULL,
    id_ejercicio integer NOT NULL,
    orden integer NOT NULL,
    series character varying(50),
    repeticiones character varying(50),
    carga character varying(50),
    descanso character varying(50),
    observacion text,
    bloque character varying(10),
    dia integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.rutina_detalle OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 57479)
-- Name: rutina_detalle_cargas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rutina_detalle_cargas (
    id_detalle bigint NOT NULL,
    carga_indice integer NOT NULL,
    carga_valor character varying(50)
);


ALTER TABLE public.rutina_detalle_cargas OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 57443)
-- Name: rutina_detalle_id_detalle_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.rutina_detalle_id_detalle_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.rutina_detalle_id_detalle_seq OWNER TO postgres;

--
-- TOC entry 5208 (class 0 OID 0)
-- Dependencies: 245
-- Name: rutina_detalle_id_detalle_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.rutina_detalle_id_detalle_seq OWNED BY public.rutina_detalle.id_detalle;


--
-- TOC entry 240 (class 1259 OID 25156)
-- Name: rutina_id_rutina_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.rutina_id_rutina_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.rutina_id_rutina_seq OWNER TO postgres;

--
-- TOC entry 5209 (class 0 OID 0)
-- Dependencies: 240
-- Name: rutina_id_rutina_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.rutina_id_rutina_seq OWNED BY public.rutina.id_rutina;


--
-- TOC entry 219 (class 1259 OID 24706)
-- Name: socio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socio (
    dni character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    telefono character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    fecha_nacimiento date NOT NULL,
    activo boolean
);


ALTER TABLE public.socio OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 24820)
-- Name: socio_membresia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socio_membresia (
    id_sm integer NOT NULL,
    dni_socio character varying(255) NOT NULL,
    id_membresia integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_hasta date,
    precio numeric(10,2),
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT socio_membresia_precio_check CHECK ((precio > (0)::numeric))
);


ALTER TABLE public.socio_membresia OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 24819)
-- Name: socio_membresia_id_sm_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.socio_membresia_id_sm_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.socio_membresia_id_sm_seq OWNER TO postgres;

--
-- TOC entry 5210 (class 0 OID 0)
-- Dependencies: 232
-- Name: socio_membresia_id_sm_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.socio_membresia_id_sm_seq OWNED BY public.socio_membresia.id_sm;


--
-- TOC entry 241 (class 1259 OID 32774)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    password character varying(255) NOT NULL,
    rol character varying(255),
    username character varying(255),
    empleado_dni character varying(255),
    socio_dni character varying(255),
    CONSTRAINT usuario_rol_check CHECK (((rol)::text = ANY ((ARRAY['ADMIN'::character varying, 'SOCIO'::character varying, 'EMPLEADO'::character varying])::text[])))
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 32790)
-- Name: usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuario_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuario_seq OWNER TO postgres;

--
-- TOC entry 4947 (class 2604 OID 41088)
-- Name: ejercicio id_ejercicio; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ejercicio ALTER COLUMN id_ejercicio SET DEFAULT nextval('public.ejercicio_id_ejercicio_seq'::regclass);


--
-- TOC entry 4946 (class 2604 OID 32826)
-- Name: grupo_muscular id_grupo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grupo_muscular ALTER COLUMN id_grupo SET DEFAULT nextval('public.grupo_muscular_id_grupo_seq'::regclass);


--
-- TOC entry 4939 (class 2604 OID 32864)
-- Name: medio_pago id_mediopago; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medio_pago ALTER COLUMN id_mediopago SET DEFAULT nextval('public.medio_pago_id_mediopago_seq'::regclass);


--
-- TOC entry 4935 (class 2604 OID 41098)
-- Name: membresia id_membresia; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membresia ALTER COLUMN id_membresia SET DEFAULT nextval('public.membresia_id_membresia_seq'::regclass);


--
-- TOC entry 4940 (class 2604 OID 41048)
-- Name: pago id_pago; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pago ALTER COLUMN id_pago SET DEFAULT nextval('public.pago_id_pago_seq'::regclass);


--
-- TOC entry 4936 (class 2604 OID 41078)
-- Name: producto id_producto; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto ALTER COLUMN id_producto SET DEFAULT nextval('public.producto_id_producto_seq'::regclass);


--
-- TOC entry 4932 (class 2604 OID 25050)
-- Name: puesto id_puesto; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puesto ALTER COLUMN id_puesto SET DEFAULT nextval('public.puesto_id_puesto_seq'::regclass);


--
-- TOC entry 4949 (class 2604 OID 41068)
-- Name: rutina id_rutina; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rutina ALTER COLUMN id_rutina SET DEFAULT nextval('public.rutina_id_rutina_seq'::regclass);


--
-- TOC entry 4953 (class 2604 OID 57447)
-- Name: rutina_detalle id_detalle; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rutina_detalle ALTER COLUMN id_detalle SET DEFAULT nextval('public.rutina_detalle_id_detalle_seq'::regclass);


--
-- TOC entry 4942 (class 2604 OID 41058)
-- Name: socio_membresia id_sm; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socio_membresia ALTER COLUMN id_sm SET DEFAULT nextval('public.socio_membresia_id_sm_seq'::regclass);


--
-- TOC entry 5012 (class 2606 OID 41090)
-- Name: ejercicio ejercicio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ejercicio
    ADD CONSTRAINT ejercicio_pkey PRIMARY KEY (id_ejercicio);


--
-- TOC entry 4979 (class 2606 OID 24953)
-- Name: empleado empleado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT empleado_pkey PRIMARY KEY (dni);


--
-- TOC entry 5024 (class 2606 OID 49227)
-- Name: gasto gasto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gasto
    ADD CONSTRAINT gasto_pkey PRIMARY KEY (id_gasto);


--
-- TOC entry 5010 (class 2606 OID 32828)
-- Name: grupo_muscular grupo_muscular_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grupo_muscular
    ADD CONSTRAINT grupo_muscular_pkey PRIMARY KEY (id_grupo);


--
-- TOC entry 4997 (class 2606 OID 32866)
-- Name: medio_pago medio_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medio_pago
    ADD CONSTRAINT medio_pago_pkey PRIMARY KEY (id_mediopago);


--
-- TOC entry 4985 (class 2606 OID 41100)
-- Name: membresia membresia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membresia
    ADD CONSTRAINT membresia_pkey PRIMARY KEY (id_membresia);


--
-- TOC entry 5002 (class 2606 OID 41050)
-- Name: pago pago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT pago_pkey PRIMARY KEY (id_pago);


--
-- TOC entry 4975 (class 2606 OID 41042)
-- Name: asistencia pk_asistencia; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asistencia
    ADD CONSTRAINT pk_asistencia PRIMARY KEY (dni, fecha_hora);


--
-- TOC entry 5008 (class 2606 OID 24852)
-- Name: detalle_pago pk_detalle_pago; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_pago
    ADD CONSTRAINT pk_detalle_pago PRIMARY KEY (id_pago, numero);


--
-- TOC entry 4993 (class 2606 OID 41080)
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id_producto);


--
-- TOC entry 4977 (class 2606 OID 25052)
-- Name: puesto puesto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puesto
    ADD CONSTRAINT puesto_pkey PRIMARY KEY (id_puesto);


--
-- TOC entry 5029 (class 2606 OID 57485)
-- Name: rutina_detalle_cargas rutina_detalle_cargas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rutina_detalle_cargas
    ADD CONSTRAINT rutina_detalle_cargas_pkey PRIMARY KEY (id_detalle, carga_indice);


--
-- TOC entry 5026 (class 2606 OID 57455)
-- Name: rutina_detalle rutina_detalle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rutina_detalle
    ADD CONSTRAINT rutina_detalle_pkey PRIMARY KEY (id_detalle);


--
-- TOC entry 5014 (class 2606 OID 41070)
-- Name: rutina rutina_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rutina
    ADD CONSTRAINT rutina_pkey PRIMARY KEY (id_rutina);


--
-- TOC entry 5006 (class 2606 OID 41060)
-- Name: socio_membresia socio_membresia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socio_membresia
    ADD CONSTRAINT socio_membresia_pkey PRIMARY KEY (id_sm);


--
-- TOC entry 4968 (class 2606 OID 25091)
-- Name: socio socio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socio
    ADD CONSTRAINT socio_pkey PRIMARY KEY (dni);


--
-- TOC entry 5016 (class 2606 OID 32787)
-- Name: usuario uk530j7rtbay29tq6vql64l8eyr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk530j7rtbay29tq6vql64l8eyr UNIQUE (empleado_dni);


--
-- TOC entry 5018 (class 2606 OID 32785)
-- Name: usuario uk863n1y3x0jalatoir4325ehal; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username);


--
-- TOC entry 4987 (class 2606 OID 25191)
-- Name: membresia uk_membresia_nombre; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membresia
    ADD CONSTRAINT uk_membresia_nombre UNIQUE (nombre);


--
-- TOC entry 4995 (class 2606 OID 25189)
-- Name: producto uk_producto_nombre; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT uk_producto_nombre UNIQUE (nombre);


--
-- TOC entry 5020 (class 2606 OID 32789)
-- Name: usuario ukgodi4hidljjivn4374hm7kp1e; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT ukgodi4hidljjivn4374hm7kp1e UNIQUE (socio_dni);


--
-- TOC entry 4981 (class 2606 OID 41037)
-- Name: empleado uq_empleado_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT uq_empleado_email UNIQUE (email);


--
-- TOC entry 4983 (class 2606 OID 41039)
-- Name: empleado uq_empleado_telefono; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT uq_empleado_telefono UNIQUE (telefono);


--
-- TOC entry 4989 (class 2606 OID 65691)
-- Name: membresia uq_membresia_nombre_tipo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membresia
    ADD CONSTRAINT uq_membresia_nombre_tipo UNIQUE (nombre, tipo_membresia);


--
-- TOC entry 4991 (class 2606 OID 41031)
-- Name: membresia uq_nombre_tipo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membresia
    ADD CONSTRAINT uq_nombre_tipo UNIQUE (nombre, tipo_membresia);


--
-- TOC entry 4970 (class 2606 OID 41033)
-- Name: socio uq_socio_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socio
    ADD CONSTRAINT uq_socio_email UNIQUE (email);


--
-- TOC entry 4972 (class 2606 OID 41035)
-- Name: socio uq_socio_telefono; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socio
    ADD CONSTRAINT uq_socio_telefono UNIQUE (telefono);


--
-- TOC entry 5022 (class 2606 OID 32783)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4973 (class 1259 OID 65676)
-- Name: idx_asistencia_fecha_hora; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_asistencia_fecha_hora ON public.asistencia USING btree (fecha_hora);


--
-- TOC entry 4998 (class 1259 OID 65674)
-- Name: idx_pago_dni_socio; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pago_dni_socio ON public.pago USING btree (dni_socio);


--
-- TOC entry 4999 (class 1259 OID 65675)
-- Name: idx_pago_estado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pago_estado ON public.pago USING btree (estado);


--
-- TOC entry 5000 (class 1259 OID 65673)
-- Name: idx_pago_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pago_fecha ON public.pago USING btree (fecha);


--
-- TOC entry 5027 (class 1259 OID 57491)
-- Name: idx_rutina_detalle_cargas_detalle; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_rutina_detalle_cargas_detalle ON public.rutina_detalle_cargas USING btree (id_detalle);


--
-- TOC entry 5003 (class 1259 OID 65677)
-- Name: idx_socio_membresia_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_socio_membresia_fecha ON public.socio_membresia USING btree (fecha_hasta, activo);


--
-- TOC entry 5004 (class 1259 OID 65678)
-- Name: idx_socio_membresia_socio; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_socio_membresia_socio ON public.socio_membresia USING btree (dni_socio);


--
-- TOC entry 5043 (class 2606 OID 32791)
-- Name: usuario fk83d0bvnltdmi7yix6amtj3ve; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT fk83d0bvnltdmi7yix6amtj3ve FOREIGN KEY (empleado_dni) REFERENCES public.empleado(dni);


--
-- TOC entry 5030 (class 2606 OID 25098)
-- Name: asistencia fk_asis_socio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asistencia
    ADD CONSTRAINT fk_asis_socio FOREIGN KEY (dni) REFERENCES public.socio(dni);


--
-- TOC entry 5037 (class 2606 OID 41052)
-- Name: detalle_pago fk_dp_pago; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_pago
    ADD CONSTRAINT fk_dp_pago FOREIGN KEY (id_pago) REFERENCES public.pago(id_pago) ON DELETE CASCADE;


--
-- TOC entry 5038 (class 2606 OID 41082)
-- Name: detalle_pago fk_dp_producto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_pago
    ADD CONSTRAINT fk_dp_producto FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);


--
-- TOC entry 5039 (class 2606 OID 41062)
-- Name: detalle_pago fk_dp_sm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_pago
    ADD CONSTRAINT fk_dp_sm FOREIGN KEY (id_sm) REFERENCES public.socio_membresia(id_sm);


--
-- TOC entry 5040 (class 2606 OID 32830)
-- Name: ejercicio fk_ejer_grupo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ejercicio
    ADD CONSTRAINT fk_ejer_grupo FOREIGN KEY (id_grupo) REFERENCES public.grupo_muscular(id_grupo) ON DELETE CASCADE;


--
-- TOC entry 5031 (class 2606 OID 25054)
-- Name: empleado fk_emp_puesto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT fk_emp_puesto FOREIGN KEY (id_puesto) REFERENCES public.puesto(id_puesto);


--
-- TOC entry 5045 (class 2606 OID 49228)
-- Name: gasto fk_gasto_mediopago; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gasto
    ADD CONSTRAINT fk_gasto_mediopago FOREIGN KEY (id_mediopago) REFERENCES public.medio_pago(id_mediopago);


--
-- TOC entry 5032 (class 2606 OID 25024)
-- Name: pago fk_pago_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT fk_pago_empleado FOREIGN KEY (dni_empleado) REFERENCES public.empleado(dni);


--
-- TOC entry 5033 (class 2606 OID 32868)
-- Name: pago fk_pago_mediopago; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT fk_pago_mediopago FOREIGN KEY (id_mediopago) REFERENCES public.medio_pago(id_mediopago);


--
-- TOC entry 5034 (class 2606 OID 25103)
-- Name: pago fk_pago_socio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT fk_pago_socio FOREIGN KEY (dni_socio) REFERENCES public.socio(dni);


--
-- TOC entry 5048 (class 2606 OID 57486)
-- Name: rutina_detalle_cargas fk_rutina_detalle_cargas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rutina_detalle_cargas
    ADD CONSTRAINT fk_rutina_detalle_cargas FOREIGN KEY (id_detalle) REFERENCES public.rutina_detalle(id_detalle) ON DELETE CASCADE;


--
-- TOC entry 5041 (class 2606 OID 25080)
-- Name: rutina fk_rutina_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rutina
    ADD CONSTRAINT fk_rutina_empleado FOREIGN KEY (dni_empleado) REFERENCES public.empleado(dni) ON DELETE SET NULL;


--
-- TOC entry 5042 (class 2606 OID 25108)
-- Name: rutina fk_rutina_socio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rutina
    ADD CONSTRAINT fk_rutina_socio FOREIGN KEY (dni_socio) REFERENCES public.socio(dni) ON DELETE CASCADE;


--
-- TOC entry 5035 (class 2606 OID 41102)
-- Name: socio_membresia fk_sm_membresia; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socio_membresia
    ADD CONSTRAINT fk_sm_membresia FOREIGN KEY (id_membresia) REFERENCES public.membresia(id_membresia);


--
-- TOC entry 5036 (class 2606 OID 25149)
-- Name: socio_membresia fk_sm_socio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socio_membresia
    ADD CONSTRAINT fk_sm_socio FOREIGN KEY (dni_socio) REFERENCES public.socio(dni);


--
-- TOC entry 5044 (class 2606 OID 32796)
-- Name: usuario fkr0tucbqhcvv223ylm3ajgqjr3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT fkr0tucbqhcvv223ylm3ajgqjr3 FOREIGN KEY (socio_dni) REFERENCES public.socio(dni);


--
-- TOC entry 5046 (class 2606 OID 57456)
-- Name: rutina_detalle rutina_detalle_id_ejercicio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rutina_detalle
    ADD CONSTRAINT rutina_detalle_id_ejercicio_fkey FOREIGN KEY (id_ejercicio) REFERENCES public.ejercicio(id_ejercicio);


--
-- TOC entry 5047 (class 2606 OID 57461)
-- Name: rutina_detalle rutina_detalle_id_rutina_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rutina_detalle
    ADD CONSTRAINT rutina_detalle_id_rutina_fkey FOREIGN KEY (id_rutina) REFERENCES public.rutina(id_rutina);


-- Completed on 2026-02-10 01:52:51

--
-- PostgreSQL database dump complete
--

\unrestrict wXuWLZSTozvq6T2RXDL4ScJ8tg8knKGYgLjosuexL1ABcUgNH5oAeVtc0qIgfbE

