-- V1: Schema Inicial (Sincronizado con Producción)

-- Tablas
CREATE TABLE IF NOT EXISTS public.asistencia (
    dni character varying(255) NOT NULL,
    fecha_hora timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado_asistencia character varying(255),
    CONSTRAINT pk_asistencia PRIMARY KEY (dni, fecha_hora)
);

CREATE TABLE IF NOT EXISTS public.grupo_muscular (
    id_grupo SERIAL PRIMARY KEY,
    nombre character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.ejercicio (
    id_ejercicio SERIAL PRIMARY KEY,
    id_grupo integer NOT NULL,
    nombre character varying(255) NOT NULL,
    video_url character varying(255),
    descripcion character varying(255),
    CONSTRAINT fk_ejer_grupo FOREIGN KEY (id_grupo) REFERENCES public.grupo_muscular(id_grupo) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.puesto (
    id_puesto SERIAL PRIMARY KEY,
    nombre character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.empleado (
    dni character varying(255) PRIMARY KEY,
    nombre character varying(255) NOT NULL,
    telefono character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    fecha_nacimiento date NOT NULL,
    id_puesto integer NOT NULL,
    fecha_inicio date DEFAULT CURRENT_DATE,
    activo boolean DEFAULT true,
    CONSTRAINT uq_empleado_email UNIQUE (email),
    CONSTRAINT uq_empleado_telefono UNIQUE (telefono),
    CONSTRAINT fk_emp_puesto FOREIGN KEY (id_puesto) REFERENCES public.puesto(id_puesto)
);

CREATE TABLE IF NOT EXISTS public.socio (
    dni character varying(255) PRIMARY KEY,
    nombre character varying(255) NOT NULL,
    telefono character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    fecha_nacimiento date NOT NULL,
    activo boolean,
    CONSTRAINT uq_socio_email UNIQUE (email),
    CONSTRAINT uq_socio_telefono UNIQUE (telefono)
);

CREATE TABLE IF NOT EXISTS public.usuario (
    id BIGSERIAL PRIMARY KEY,
    activo boolean NOT NULL,
    password character varying(255) NOT NULL,
    rol character varying(255),
    username character varying(255),
    empleado_dni character varying(255),
    socio_dni character varying(255),
    CONSTRAINT uk_username UNIQUE (username),
    CONSTRAINT uk_usuario_empleado UNIQUE (empleado_dni),
    CONSTRAINT uk_usuario_socio UNIQUE (socio_dni),
    CONSTRAINT usuario_rol_check CHECK (rol IN ('ADMIN', 'SOCIO', 'EMPLEADO')),
    CONSTRAINT fk_usuario_empleado FOREIGN KEY (empleado_dni) REFERENCES public.empleado(dni),
    CONSTRAINT fk_usuario_socio FOREIGN KEY (socio_dni) REFERENCES public.socio(dni)
);

CREATE TABLE IF NOT EXISTS public.medio_pago (
    id_mediopago SERIAL PRIMARY KEY,
    nombre character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.gasto (
    id_gasto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    monto numeric(10,2) NOT NULL,
    categoria character varying(255) NOT NULL,
    proveedor character varying(255) NOT NULL,
    id_mediopago integer NOT NULL,
    activo boolean DEFAULT true,
    CONSTRAINT gasto_categoria_check CHECK (categoria IN ('ALQUILER', 'SERVICIOS', 'SUELDOS', 'INSUMOS')),
    CONSTRAINT gasto_monto_check CHECK (monto > 0),
    CONSTRAINT fk_gasto_mediopago FOREIGN KEY (id_mediopago) REFERENCES public.medio_pago(id_mediopago)
);

CREATE TABLE IF NOT EXISTS public.membresia (
    id_membresia SERIAL PRIMARY KEY,
    nombre character varying(255) NOT NULL,
    duracion_dias integer NOT NULL,
    precio_sugerido numeric(10,2) NOT NULL,
    activo boolean,
    asistencias_por_semana integer,
    tipo_membresia character varying(255),
    CONSTRAINT membresia_duracion_dias_check CHECK (duracion_dias > 0),
    CONSTRAINT membresia_precio_sugerido_check CHECK (precio_sugerido > 0),
    CONSTRAINT membresia_tipo_membresia_check CHECK (tipo_membresia IN ('MUSCULACION', 'FUNCIONAL', 'MIXTA')),
    CONSTRAINT uq_membresia_nombre UNIQUE (nombre),
    CONSTRAINT uq_membresia_nombre_tipo UNIQUE (nombre, tipo_membresia)
);

CREATE TABLE IF NOT EXISTS public.socio_membresia (
    id_sm SERIAL PRIMARY KEY,
    dni_socio character varying(255) NOT NULL,
    id_membresia integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_hasta date,
    precio numeric(10,2),
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT socio_membresia_precio_check CHECK (precio > 0),
    CONSTRAINT fk_sm_socio FOREIGN KEY (dni_socio) REFERENCES public.socio(dni),
    CONSTRAINT fk_sm_membresia FOREIGN KEY (id_membresia) REFERENCES public.membresia(id_membresia)
);

CREATE TABLE IF NOT EXISTS public.pago (
    id_pago SERIAL PRIMARY KEY,
    id_mediopago integer NOT NULL,
    dni_empleado character varying(255) NOT NULL,
    dni_socio character varying(255),
    estado character varying(255) NOT NULL,
    fecha date DEFAULT CURRENT_DATE,
    monto numeric(10,2) NOT NULL,
    CONSTRAINT fk_pago_empleado FOREIGN KEY (dni_empleado) REFERENCES public.empleado(dni),
    CONSTRAINT fk_pago_mediopago FOREIGN KEY (id_mediopago) REFERENCES public.medio_pago(id_mediopago),
    CONSTRAINT fk_pago_socio FOREIGN KEY (dni_socio) REFERENCES public.socio(dni)
);

CREATE TABLE IF NOT EXISTS public.producto (
    id_producto SERIAL PRIMARY KEY,
    nombre character varying(255) NOT NULL,
    precio_sugerido numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    version integer DEFAULT 0,
    CONSTRAINT chk_producto_stock_no_negativo CHECK (stock >= 0),
    CONSTRAINT producto_precio_sugerido_check CHECK (precio_sugerido > 0),
    CONSTRAINT uk_producto_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.detalle_pago (
    id_pago integer NOT NULL,
    numero integer NOT NULL,
    id_producto integer,
    id_sm integer,
    cantidad integer DEFAULT 1,
    precio_unitario numeric(10,2) NOT NULL,
    subtotal numeric(10,2) GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,
    CONSTRAINT pk_detalle_pago PRIMARY KEY (id_pago, numero),
    CONSTRAINT ck_producto_o_membresia CHECK ((id_producto IS NULL AND id_sm IS NOT NULL) OR (id_producto IS NOT NULL AND id_sm IS NULL)),
    CONSTRAINT detalle_pago_precio_unitario_check CHECK (precio_unitario > 0),
    CONSTRAINT fk_dp_pago FOREIGN KEY (id_pago) REFERENCES public.pago(id_pago) ON DELETE CASCADE,
    CONSTRAINT fk_dp_producto FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto),
    CONSTRAINT fk_dp_sm FOREIGN KEY (id_sm) REFERENCES public.socio_membresia(id_sm)
);

CREATE TABLE IF NOT EXISTS public.rutina (
    id_rutina SERIAL PRIMARY KEY,
    nombre character varying(255) NOT NULL,
    descripcion character varying(255),
    fecha date DEFAULT CURRENT_DATE,
    dni_socio character varying(255),
    dni_empleado character varying(255),
    id_plantilla_origen integer,
    personalizada boolean DEFAULT false NOT NULL,
    CONSTRAINT fk_rutina_empleado FOREIGN KEY (dni_empleado) REFERENCES public.empleado(dni) ON DELETE SET NULL,
    CONSTRAINT fk_rutina_socio FOREIGN KEY (dni_socio) REFERENCES public.socio(dni) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.rutina_detalle (
    id_detalle BIGSERIAL PRIMARY KEY,
    id_rutina integer NOT NULL,
    id_ejercicio integer NOT NULL,
    orden integer NOT NULL,
    series character varying(50),
    repeticiones character varying(50),
    carga character varying(50),
    descanso character varying(50),
    observacion text,
    bloque character varying(10),
    dia integer DEFAULT 1 NOT NULL,
    CONSTRAINT fk_rutina_detalle_rutina FOREIGN KEY (id_rutina) REFERENCES public.rutina(id_rutina),
    CONSTRAINT fk_rutina_detalle_ejercicio FOREIGN KEY (id_ejercicio) REFERENCES public.ejercicio(id_ejercicio)
);

CREATE TABLE IF NOT EXISTS public.rutina_detalle_cargas (
    id_detalle bigint NOT NULL,
    carga_indice integer NOT NULL,
    carga_valor character varying(50),
    CONSTRAINT pk_rutina_detalle_cargas PRIMARY KEY (id_detalle, carga_indice),
    CONSTRAINT fk_rutina_detalle_cargas FOREIGN KEY (id_detalle) REFERENCES public.rutina_detalle(id_detalle) ON DELETE CASCADE
);

-- Indices
CREATE INDEX IF NOT EXISTS idx_asistencia_fecha_hora ON public.asistencia(fecha_hora);
CREATE INDEX IF NOT EXISTS idx_pago_dni_socio ON public.pago(dni_socio);
CREATE INDEX IF NOT EXISTS idx_pago_estado ON public.pago(estado);
CREATE INDEX IF NOT EXISTS idx_pago_fecha ON public.pago(fecha);
CREATE INDEX IF NOT EXISTS idx_rutina_detalle_cargas_detalle ON public.rutina_detalle_cargas(id_detalle);
CREATE INDEX IF NOT EXISTS idx_socio_membresia_fecha ON public.socio_membresia(fecha_hasta, activo);
CREATE INDEX IF NOT EXISTS idx_socio_membresia_socio ON public.socio_membresia(dni_socio);
